Document Validation flow
slovensko-digital/avm-app-flutter pull request #72
Opened 2024-11-16 18:36 UTC by Matej-Hlatky

Closes #36

2024-11-17 16:02 UTC, celuchmarek requested changes
Nainštaloval som si posledný build z tejto branche. Overovanie podpisov funguje v poriadku. Rovnako funguje v poridaku aj podpisovanie lokálneho súboru.

Pri podpisovaní cez QR kód zostane na konci appka v "loading" stave, aj keď extension podpísaný dokument normálne dostane a úspešne dokončí podpisovnaie na webe. Nechal som appku aj minútu v tomto stave a nepohla sa ďalej. Back button ma vráti na home screen a viem appku ďalej používať. Pri podpise lokálneho súboru problém nenastáva.
![Screenshot_2024-11-17-16-56-15-516_digital slovensko avm](https://github.com/user-attachments/assets/8b615850-1dd2-4a16-bf90-e4a63a832555)

2024-11-17 18:36 UTC, celuchmarek approved these changes
Hlásený problém sme fixli v druhom PR. Mergneme ich naraz, takže ok.

2024-11-18 08:23 UTC, celuchmarek commented
Pridávam screenshoty, aby sme vedeli, ako to vyzerá cc @jsuchal 
![Snímka obrazovky 2024-11-18 o 9 22 26](https://github.com/user-attachments/assets/eda01bf4-0914-4ae5-8ab4-08cb83d46c59)

2024-11-18 11:47 UTC, merged

2024-11-25 23:40 UTC, tajovic commented
Kukol som výsledky testovania pre overovanie podpisov. Vypadli z neho 3 veci:

### Fičúra je trochu skrytá 
Za mňa je toto dobré pretože:
- overovanie podpisov nie je najhlavnejší cieľ aplikácie (to je podpisovanie);
- skúsenejší používatelia ju vedia použiť a menej skúseným to zo začiatku ušetrí zbytočné komplikácie;
- keďže (ak mám správne info) sa drvivá väčšina dokumentov podpisuje jedným podpisom / osobou.

Flow bol navrhnutý tak aby sa pred podpisom skontrolovali dokumenty a v prípade nejakých problémov bol používateľ upozornený, takže nejaké fatálne následky by nastať rozhodne nemali ani pri začiatočníkoch. 

Zatiaľ by som sa teda tomuto bodu viac nevenoval a bral to skôr ako fičurú a nie bug.

### Nesedela terminológia
Úprimne si už nepamätám či som niečo nekonzistentne pomenoval v prototype, je to dosť možné. Dajte si iba prosím pozor, aby sa typy podpisov v tomto flowe volali rovnako ako počas podpisovania, resp. ako je to zaužívané medzi používateľmi. Malo by to potom byť v poriadku.

### Chýbali podrobnosti
Ľudia hovorili, že by sa radi dozvedeli viac informacii v prípadoch neplatných podpisov, aby vedeli čo teda majú robiť. Na jednu stranu sme AVM nechceli veľmi komplikovať a chceli to skôr spraviť jednoduchšie na používanie, na druhej dáva zmysel, že keď človek nájde nejaký nedostatok, rád by vedeľ čo má vtedy robiť. 

Zároveň metodológia toho konkrétneho testovania použiteľnosti z hackathonu nebola najvhodnejšia na otestovanie toho, ako by sa používatelia reálne správali v takej situácii a čo by potrebovali. Bolo to príliš hypotetícké a odrážame sa v podstate iba od tvrdení, nie pozorovania.

Môžeme (nemusíme) teda otvoriť debatu či pri neplatných, neznámych a iných ne- typoch podpisov nechceme zobrazovať aj nejaké dodatočné info o tom čo to znamená, ako sa to asi mohlo stať a čo s tým môže používateľ robiť ďalej. Toto je však na sync a trochu dizajnovania, tak si povedzte x)